### ISSUE TITLE
之前注册的账号突然登录不了了

### ISSUE THREAD

**Issue by handbye** [Zer0ne-Sec/ngxpt#13]
![image](https://user-images.githubusercontent.com/26617058/135011640-0a184bf2-e3d0-404a-a8cd-35ced09a6af0.png)
提示登录失败，用户名bingoyes
密码是没改过的，前几天登录还可以的。

**Comment by Amzza0x00** [comment]
兄弟，你的号上一次登录时间为2021-08-10 21:58:31，回忆下密码吧。

**Comment by handbye** [comment]
密码多了个空格。。。，已登录成功。
